blog/urls.py
from django.urls import path
from blog.apps import BlogModelConfig
from django.conf import settings

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView
from . import views

app_name = BlogModelConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('detail/<int:pk>', BlogDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),

]

catalog/urls.py
from django.urls import path
from django.contrib import admin
from catalog.apps import CatalogConfig
from catalog.views import contacts, info1, ProductCreateView, ProductDetailView, ProductListView, ProductUpdateView, \
    ProductDeleteView
from django.conf.urls.static import static
from django.conf import settings

app_name = CatalogConfig.name




urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', index, name='index'),
    path('contacts/', contacts, name='contact'),
    path('info1/', info1, name='info1'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('', ProductListView.as_view(), name='list'),
    path('view/<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
              ]

blog/models.py
from django.db import models
from datetime import datetime

from django.utils.text import slugify

NULLABLE = {"null": True, "blank": True}

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    conteхt = models.TextField(verbose_name='Содержимое')
    preview_img = models.ImageField(upload_to='blog/images/', verbose_name='Превью(изображение)', **NULLABLE)
    now = datetime.now()
    current_time = now.strftime("%Y-%m-%d")
    date_create = models.DateField(verbose_name='Дата создания', default=current_time)
    is_published = models.BooleanField(verbose_name='Признак публикации', default=True)

    view_count = models.IntegerField(default=0, verbose_name='просмотры')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    def __str__(self):
        return f'{self.title}'


class Meta:
    verbose_name = 'блог'
    verbose_name_plural = 'блога'
    ordering = ('title',)

catalog/models.py
from datetime import datetime

from django.db import models

NULLABLE = {"null": True, "blank": True}


class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name='наименование')
    description= models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.category_name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('category_name',)

class Product(models.Model):
    product_name = models.CharField(max_length=100, verbose_name='наименование')
    product_description = models.TextField(verbose_name='описание')
    avatar = models.ImageField(upload_to='products/', verbose_name='изображение(превью)', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория',**NULLABLE)
    price = models.FloatField(verbose_name='цена за покупку')
    quantity_product = models.IntegerField(verbose_name='количество', default=0)
    now = datetime.now()
    current_time = now.strftime("%d.%m.%Y")
    date_create = models.DateField(verbose_name='дата создания', default=current_time)
    date_last_change = models.DateField(verbose_name='дата последнего изменения',default=current_time)

    views_count = models.IntegerField(default=0, verbose_name='просмотры')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return f'{self.product_name}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('product_name',)

blog/views.py
# Create your views here.
from django.urls import reverse_lazy, reverse

from blog.models import Blog
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'conteхt')
    success_url = reverse_lazy('blog:list')



class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'conteхt')
    success_url = reverse_lazy('blog:list')

    def get_success_url(self):
        return reverse('blog:detail', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog
    context_object_name = 'object_list'

    def get_queryset(self):
       return Blog.objects.filter(is_published=True)


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'
    context_object_name = 'object'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

catalog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy


from catalog.models import Category, Product
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView


# Create your views here.

#def index(request):
#    product_list = Product.objects.all()
#    context = {
#        'objects_list': product_list
#    }
#    return render(request, 'catalog/index.html', context=context)


def contacts(request):
    return render(request,'catalog/contacts.html')

def info1(request):

    return render(request,'catalog/info1.html')

class ProductCreateView(CreateView):
    model = Product, Category
    fields = ('product_name', 'product_description')
    success_url = reverse_lazy('catalog:list')

class ProductUpdateView(UpdateView):
    model = Product, Category
    fields = ('product_name', 'product_description')
    success_url = reverse_lazy('catalog:list')

class ProductListView(ListView):
    model = Product
    template_name = 'catalog/catalog.html'
    context_object_name = 'products'

class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'
    context_object_name = 'product'
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count +=1
        self.object.save()
        return self.object



class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">

<div class="row">

    <div class="col-md-6">
            <h1 class="card-title">Удаление записи</h1>

        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Желаете удалить запись "{{object.title}} ?</p>

                    <button type="submit" class="btn btn-success">Подтвердить</button>
                    <a href="{% url 'blog:list' %}"  class="btn btn-sm btn-outline-secondary">Отмена</a>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <h1>{{ object.title }}</h1>
    <p>Описание : {{ object.conteхt }}
    </p>
    <p>Дата создания : {{ object.date_create }}</p>
    <p>Количество просмотров : {{ object.view_count }}</p>
</div>
            <a href="{% url 'blog:list' %}" class="btn btn-secondary">назад</a>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends "catalog/base.html" %}
{% block content %}

<div class="row">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary" >
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        <a href="{% url 'blog:list' %}" class="btn btn-secondary">назад</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="container">
    <div class="row justify-content-center mb-5">
        <div class="col-md-2">
            <a class="btn btn-primary btn-block" href="{% url 'blog:create' %}">Добавить запись</a>
        </div>
    </div>
    <h1>Список записей</h1>

    <ul>
        {% for object in object_list %}
        <li>
            <h2><a href="{% url 'blog:detail' object.pk %}">{{ object.title }}</a></h2>
            <p>{{ object.context }}</p>
            <p>Просмотры: {{ object.view_count }}</p>
            <a href="{% url 'blog:detail' object.pk %}" class="btn btn-secondary">View</a>
            <a href="{% url 'blog:edit' object.pk %}" class="btn btn-secondary">Edit</a>
            <a href="{% url 'blog:delete' object.pk %}" class="btn btn-secondary">Delete</a>
        </li>
        {% endfor %}
    </ul>`
</div>
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>ElektroStore</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="{%  static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{%  static 'css/album.css' %}" rel="stylesheet">
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="/blog/" class="text-white">Блог магазина </a></li>
                <li><a href="#" class="text-white">Like on Facebook</a></li>
                <li><a href="#" class="text-white">Email me</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Album</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Магазин электроники ElektroStore</h1>
          <p class="lead text-muted">Магазин электроники ElektroStore - это отличный вариант вложения ваших денежных средств</p>
          <p>
            <a  class="btn btn-primary my-2" href="/" >Каталог</a>
            <a  class="btn btn-secondary my-2" href="/contacts" >Контакты</a>
            <a  class="btn btn-secondary my-2" href="/create" >Добавить товар</a>

          </p>
        </div>

</section>

      <div class="album py-5 bg-light">

        <div class="container">

          <div class="row">


          {% block content %}
          {% endblock %}



  </div>
          </div>

      </div>



    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="{%  static 'js/popper.min.js' %}"></script>
    <script src="{%  static 'js/bootstrap.min.js' %}"></script>
    <script src="{%  static 'js/holder.min.js' %}"></script>
  </body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Контакты</title>
</head>
<body>
<div class="card mb-4 box-shadow">

    <div class="card-header">
        <h4 class="my-0 font-weight-normal">Контактная информация</h4>
    </div>
        <div class="card-body">
        <h2 class="card-title pricing-card-title">адрес: г.Москва Кремль</h2>
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>- тел. +7-495- 222222222</li>
        </ul>
    </div>
</div>
</body>
</html>
{% endblock %}

catalog/templates/catalog/info1.html
{% extends 'catalog/base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>куплено</title>
</head>
<body>
<h1>денег нет</h1>
</body>
</html>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
                            <h1 class="card-title">Удаление товара</h1>

<div class="row">

    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить товар "{{object.name}}</p>

                    <button type="submit" class="btn btn-success">Подтвердить</button>
                    <a href="{% url 'catalog:list' %}"  class="btn btn-sm btn-outline-secondary">Отмена</a>

                </form>
            </div>
        </div>
    </div>
    <div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}

            <div class="col-md-4">
              <div class="card mb-4 box-shadow">

                  <img src="media:{{object.avatar }}" alt="нет изображения"  style="max-width: 50%;">

                <div class="card-body">
                    <h5 class="card-title">{{object.category|title}} {{object.product_name|title}}</h5>
                    <h1 class="card-title pricing-card-title">{{object.price|floatformat:2}} руб.</h1>
                  <p class="card-text">{{object.product_description|truncatechars:100}}</p>
                    <a class="pb-1  mb-4 btn btn-outline-primary form-control" href="{% url 'catalog:info1' %}">Купить</a>

                  <div class="d-flex justify-content-between align-items-center">

                    <div class="btn-group ">
                      <a href="{% url 'catalog:list' %}"  class="btn btn-sm btn-outline-secondary"  >Назад</a>


                    </div>
                    <small class="text-muted">Просмотров - {{ object.views_count }}</small>
                  </div>
                </div>
              </div>
            </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-secondary">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}

{% for object in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                  <img src="media/{{object.avatar }}" alt="нет изображения"  style="max-width: 50%;">
                      <small class="text-muted">Осталось - {{ object.quantity_product }} шт.</small>

                <div class="card-body">
                    <h5 class="card-title">{{object.category|title}} {{object.product_name|title}}</h5>
                    <h1 class="card-title pricing-card-title">{{object.price|floatformat:2}} руб.</h1>
                    <a class="pb-1  mb-4 btn btn-outline-primary form-control" href="{% url 'catalog:info1' %}">Купить</a>

                  <div class="d-flex justify-content-between align-items-center">

                    <div class="btn-group ">
                      <a href="{% url 'catalog:detail' object.pk %}"  class="btn btn-sm btn-outline-secondary"  >View</a>
                      <a href="{% url 'catalog:update' object.pk %}"  class="btn btn-sm btn-outline-secondary">Edit</a>
                      <a href="{% url 'catalog:delete' object.pk %}"  class="btn btn-sm btn-outline-secondary">Delete</a>

                    </div>
                    <small class="text-muted">Просмотров - {{ object.views_count }}</small>
                  </div>
                </div>
              </div>
            </div>
        {% endfor %}
{% endblock %}

catalog/templates/catalog/product_update.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <h1 Редактирование продукта></h1>

                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
    <div>
</div>
{% endblock %}